FROM ubuntu:22.04
WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    openssl \
    && rm -rf /var/lib/apt/lists/*

# Copy MicroMDM binaries
COPY micromdm mdmctl ./
RUN chmod +x ./micromdm ./mdmctl

# Create directories for MDM files and certificates
RUN mkdir -p mdm-certificates mdm-files

# Copy mdm-certificates file
COPY mdm-certificates ./mdm-certificates/

# Copy entrypoint script
COPY entrypoint-micromdm.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

# Expose MicroMDM port
EXPOSE 8080 443 80

# Run the entrypoint script
ENTRYPOINT ["./entrypoint.sh"]